In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
#import genotype data
genotype = pd.read_csv(
    "../data/raw/Pf8_drug_resistance_marker_genotypes.tsv",
    sep="\t"
)

In [3]:
# viewing data
genotype

,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],...,mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],kelch13_349-726_ns_changes,mdr1_dup_call,pm2_dup_call
0,FP0008-C,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
1,FP0009-C,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,Y,VD,D,T,NaN,0,0
2,FP0010-CW,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
3,FP0011-CW,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
4,FP0012-CW,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,D,VD,D,T,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24404,SPT92049,C,M,N,K,CVMNK,T,H,I,A,...,S,N,F,-,VD,D,T,-,-1,-1
24405,SPT92054,C,M,N,K,CVMNK,T,H,I,A,...,S,N,F,D,VD,D,T,NaN,0,-1
24406,SPT92057,C,M,N,K,CVMNK,T,H,I,A,...,S,N,F,D,VD,D,T,-,-1,-1
24407,SPT94772,C,I,E,T,CVIET,T,H,I,S,...,-,-,-,-,VD,D,-,-,-1,-1
24408,SPT94773,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,D,VD,D,T,NaN,0,0

In [4]:
# extract reference amino acid and create a dictionary

# Get all column names except Sample
cols = [c for c in genotype.columns if c != "Sample"]

# Dictionary: column -> reference amino acid
ref_aa = {}

for col in cols:
    m = re.search(r'\[(.*?)\]', col)
    if m:
        ref_aa[col] = m.group(1)

print(ref_aa)

{'crt_72[C]': 'C', 'crt_74[M]': 'M', 'crt_75[N]': 'N', 'crt_76[K]': 'K', 'crt_72-76[CVMNK]': 'CVMNK', 'crt_93[T]': 'T', 'crt_97[H]': 'H', 'crt_218[I]': 'I', 'crt_220[A]': 'A', 'crt_271[Q]': 'Q', 'crt_326[N]': 'N', 'crt_333[T]': 'T', 'crt_353[G]': 'G', 'crt_356[I]': 'I', 'crt_371[R]': 'R', 'dhfr_16[N]': 'N', 'dhfr_51[N]': 'N', 'dhfr_59[C]': 'C', 'dhfr_108[S]': 'S', 'dhfr_164[I]': 'I', 'dhfr_306[S]': 'S', 'dhps_436[S]': 'S', 'dhps_437[G]': 'G', 'dhps_540[K]': 'K', 'dhps_581[A]': 'A', 'dhps_613[A]': 'A', 'exo_415[E]': 'E', 'mdr1_86[N]': 'N', 'mdr1_184[Y]': 'Y', 'mdr1_1034[S]': 'S', 'mdr1_1042[N]': 'N', 'mdr1_1226[F]': 'F', 'mdr1_1246[D]': 'D', 'arps10_127-128[VD]': 'VD', 'fd_193[D]': 'D', 'mdr2_484[T]': 'T'}

In [5]:
import pandas as pd
import re

ref_df = pd.DataFrame({
    "column": genotype.columns
})

ref_df["reference"] = ref_df["column"].str.extract(r'\[(.*?)\]')

print(ref_df)

                        column reference
0                       Sample       NaN
1                    crt_72[C]         C
2                    crt_74[M]         M
3                    crt_75[N]         N
4                    crt_76[K]         K
5             crt_72-76[CVMNK]     CVMNK
6                    crt_93[T]         T
7                    crt_97[H]         H
8                   crt_218[I]         I
9                   crt_220[A]         A
10                  crt_271[Q]         Q
11                  crt_326[N]         N
12                  crt_333[T]         T
13                  crt_353[G]         G
14                  crt_356[I]         I
15                  crt_371[R]         R
16                  dhfr_16[N]         N
17                  dhfr_51[N]         N
18                  dhfr_59[C]         C
19                 dhfr_108[S]         S
20                 dhfr_164[I]         I
21                 dhfr_306[S]         S
22                 dhps_436[S]         S
23                 dhps_437[G]         G
24                 dhps_540[K]         K
25                 dhps_581[A]         A
26                 dhps_613[A]         A
27                  exo_415[E]         E
28                  mdr1_86[N]         N
29                 mdr1_184[Y]         Y
30                mdr1_1034[S]         S
31                mdr1_1042[N]         N
32                mdr1_1226[F]         F
33                mdr1_1246[D]         D
34          arps10_127-128[VD]        VD
35                   fd_193[D]         D
36                 mdr2_484[T]         T
37  kelch13_349-726_ns_changes       NaN
38               mdr1_dup_call       NaN
39                pm2_dup_call       NaN

In [6]:
ref_df.dropna(inplace =True)

In [7]:
genotype.columns

Index(['Sample', 'crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]',
       'crt_72-76[CVMNK]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]',
       'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]',
       'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]',
       'dhfr_108[S]', 'dhfr_164[I]', 'dhfr_306[S]', 'dhps_436[S]',
       'dhps_437[G]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]',
       'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]',
       'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]',
       'fd_193[D]', 'mdr2_484[T]', 'kelch13_349-726_ns_changes',
       'mdr1_dup_call', 'pm2_dup_call'],
      dtype='str')

In [8]:
ref_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 1 to 36
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   column     36 non-null     str
 1   reference  36 non-null     str
dtypes: str(2)
memory usage: 708.0 bytes

In [9]:
encoded

NameError: name 'encoded' is not defined

In [ ]:
SPECIAL = {
    "crt_76[K]": {"T"},
    "dhfr_108[S]": {"N"},
    "dhps_437[G]": {"G"},   # using the Pf8 resistance allele
}

In [ ]:
def encode(value, column):

    # Missing
    if pd.isna(value) or str(value).strip() == "":
        return "Missing"

    value = str(value).strip()

    # ---------- Special: copy number ----------
    if column in ["mdr1_dup_call", "pm2_dup_call"]:
        return "Sensitive" if int(value) == 0 else "Resistant"

    # ---------- Special: crt haplotype ----------
    if column == "crt_72-76[CVMNK]":

        haps = [x.strip() for x in value.split(",")]

        if any(h in {"CVIET", "SVMNT"} for h in haps):
            return "Resistant"

        if all(h == "CVMNK" for h in haps):
            return "Sensitive"

        return "Rare"

    # ---------- Special: kelch13 ----------
    if column == "kelch13_349-726_ns_changes":

        muts = [x.strip() for x in value.split(",")]

        if any(m in WHO_K13 for m in muts):
            return "Resistant"

        return "Rare"

    alleles = [x.strip() for x in value.split(",")]

    # ---------- Multiple alleles ----------
    if len(alleles) > 1:

        if column in SPECIAL:
            if any(a in SPECIAL[column] for a in alleles):
                return "Resistant"
            return "Rare"

        # General columns
        if ref_aa[column] in alleles:
            return "Sensitive"

        return "Rare"

    # ---------- Single allele ----------

    allele = alleles[0]

    if column in SPECIAL:
        if allele in SPECIAL[column]:
            return "Resistant"

    if allele == ref_aa[column]:
        return "Sensitive"

    return "Resistant"

In [ ]:
encoded = genotype.copy()

for col in genotype.columns:
    if col == "Sample":
        continue

    encoded[col] = genotype[col].apply(lambda x: encode(x, col))

In [ ]:
encoded

,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],...,mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],kelch13_349-726_ns_changes,mdr1_dup_call,pm2_dup_call
0,FP0008-C,Sensitive,Sensitive,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
1,FP0009-C,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Resistant,...,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
2,FP0010-CW,Sensitive,Sensitive,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
3,FP0011-CW,Sensitive,Sensitive,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
4,FP0012-CW,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Resistant,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24404,SPT92049,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Rare,Resistant,Resistant
24405,SPT92054,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Resistant
24406,SPT92057,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Rare,Resistant,Resistant
24407,SPT94772,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Resistant,...,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Resistant,Rare,Resistant,Resistant
24408,SPT94773,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Resistant,...,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive

## Filtering African countries only

In [ ]:
# getting metadata
metadata = pd.read_csv("../data/raw/Pf8-samples.csv")
metadata.head()

,sample_id,year,qc_pass,study_id,region,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,FP0008-C,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,FP0009-C,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,FP0010-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,FP0011-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,FP0012-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [ ]:
metadata['country'].unique()

<StringArray>
[                      'Mauritania',                           'Gambia',
                           'Guinea',                            'Kenya',
                         'Thailand',                         'Tanzania',
                            'Ghana',                         'Cambodia',
                        'Indonesia',                     'Burkina Faso',
                             'Mali',                 'Papua New Guinea',
                             'Peru',                       'Bangladesh',
                           'Malawi',                          'Vietnam',
                         'Colombia',                        'Venezuela',
                           'Uganda',                          'Myanmar',
                             'Laos', 'Democratic Republic of the Congo',
                          'Nigeria',                       'Madagascar',
                         'Cameroon',                    'Côte d'Ivoire',
                         'Ethiopia',                            'Benin',
                          'Senegal',                            'Gabon',
                            'India',                            'Sudan',
                       'Mozambique',                         'Honduras']
Length: 34, dtype: str

In [ ]:
# filter for High quality data
#filter_metadata = metadata['qc_pass'] == True

In [ ]:
# filtering for African data
african_countries = [
    'Mauritania',
    'Gambia',
    'Guinea',
    'Kenya',
    'Tanzania',
    'Ghana',
    'Burkina Faso',
    'Mali',
    'Malawi',
    'Uganda',
    'Democratic Republic of the Congo',
    'Nigeria',
    'Madagascar',
    'Cameroon',
    "Côte d'Ivoire",
    'Ethiopia',
    'Benin',
    'Senegal',
    'Gabon',
    'Sudan',
    'Mozambique'
]

In [ ]:
# african countries
africa_df = metadata[metadata['country'].isin(african_countries)].copy()
africa_df.info()

<class 'pandas.DataFrame'>
Index: 20951 entries, 0 to 32994
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sample_id     20951 non-null  str
 1   year          20951 non-null  int64
 2   qc_pass       20951 non-null  bool
 3   study_id      20951 non-null  int64
 4   region        0 non-null      float64
 5   country       20951 non-null  str
 6   country_id    20951 non-null  str
 7   site          20951 non-null  str
 8   site_id       20951 non-null  str
 9   ARTresistant  14508 non-null  str
 10  CQresistant   14508 non-null  str
 11  MQresistant   14508 non-null  str
 12  PPQresistant  14508 non-null  str
 13  PYRresistant  14508 non-null  str
 14  SDXresistant  14508 non-null  str
dtypes: bool(1), float64(1), int64(2), str(11)
memory usage: 2.4 MB

In [ ]:
africa_df['sample_id'].value_counts()

sample_id
FP0008-C     1
FP0009-C     1
FP0010-CW    1
FP0011-CW    1
FP0012-CW    1
            ..
SPT92268     1
SPT92269     1
SPT92270     1
SPT94772     1
SPT94773     1
Name: count, Length: 20951, dtype: int64

In [ ]:
print(len(encoded))
print(len(africa_df))

24409
20951

In [ ]:
encoded['Sample'].unique()

<StringArray>
[ 'FP0008-C',  'FP0009-C', 'FP0010-CW', 'FP0011-CW', 'FP0012-CW', 'FP0013-CW',
 'FP0014-CW',  'FP0015-C',  'FP0016-C',  'FP0017-C',
 ...
  'SPT92000',  'SPT92004',  'SPT92011',  'SPT92015',  'SPT92044',  'SPT92049',
  'SPT92054',  'SPT92057',  'SPT94772',  'SPT94773']
Length: 24409, dtype: str

In [ ]:
encoded['Sample'].value_counts()

Sample
FP0008-C     1
FP0009-C     1
FP0010-CW    1
FP0011-CW    1
FP0012-CW    1
            ..
SPT92049     1
SPT92054     1
SPT92057     1
SPT94772     1
SPT94773     1
Name: count, Length: 24409, dtype: int64

In [ ]:
# Merging with genotype encoded with africa df 
african_countries_geno = encoded.merge(africa_df, right_on = 'sample_id',left_on= 'Sample', how = 'right')

In [ ]:
print(len(african_countries_geno))

24409

In [ ]:
african_countries_geno.info()

<class 'pandas.DataFrame'>
RangeIndex: 24409 entries, 0 to 24408
Data columns (total 55 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Sample                      24409 non-null  str
 1   crt_72[C]                   24409 non-null  str
 2   crt_74[M]                   24409 non-null  str
 3   crt_75[N]                   24409 non-null  str
 4   crt_76[K]                   24409 non-null  str
 5   crt_72-76[CVMNK]            24409 non-null  str
 6   crt_93[T]                   24409 non-null  str
 7   crt_97[H]                   24409 non-null  str
 8   crt_218[I]                  24409 non-null  str
 9   crt_220[A]                  24409 non-null  str
 10  crt_271[Q]                  24409 non-null  str
 11  crt_326[N]                  24409 non-null  str
 12  crt_333[T]                  24409 non-null  str
 13  crt_353[G]                  24409 non-null  str
 14  crt_356[I]                  24409 non-null  str
 15  crt_371[R]                  24409 non-null  str
 16  dhfr_16[N]                  24409 non-null  str
 17  dhfr_51[N]                  24409 non-null  str
 18  dhfr_59[C]                  24409 non-null  str
 19  dhfr_108[S]                 24409 non-null  str
 20  dhfr_164[I]                 24409 non-null  str
 21  dhfr_306[S]                 24409 non-null  str
 22  dhps_436[S]                 24409 non-null  str
 23  dhps_437[G]                 24409 non-null  str
 24  dhps_540[K]                 24409 non-null  str
 25  dhps_581[A]                 24409 non-null  str
 26  dhps_613[A]                 24409 non-null  str
 27  exo_415[E]                  24409 non-null  str
 28  mdr1_86[N]                  24409 non-null  str
 29  mdr1_184[Y]                 24409 non-null  str
 30  mdr1_1034[S]                24409 non-null  str
 31  mdr1_1042[N]                24409 non-null  str
 32  mdr1_1226[F]                24409 non-null  str
 33  mdr1_1246[D]                24409 non-null  str
 34  arps10_127-128[VD]          24409 non-null  str
 35  fd_193[D]                   24409 non-null  str
 36  mdr2_484[T]                 24409 non-null  str
 37  kelch13_349-726_ns_changes  24409 non-null  str
 38  mdr1_dup_call               24409 non-null  str
 39  pm2_dup_call                24409 non-null  str
 40  sample_id                   14508 non-null  str
 41  year                        14508 non-null  float64
 42  qc_pass                     14508 non-null  object
 43  study_id                    14508 non-null  float64
 44  region                      0 non-null      float64
 45  country                     14508 non-null  str
 46  country_id                  14508 non-null  str
 47  site                        14508 non-null  str
 48  site_id                     14508 non-null  str
 49  ARTresistant                14508 non-null  str
 50  CQresistant                 14508 non-null  str
 51  MQresistant                 14508 non-null  str
 52  PPQresistant                14508 non-null  str
 53  PYRresistant                14508 non-null  str
 54  SDXresistant                14508 non-null  str
dtypes: float64(3), object(1), str(51)
memory usage: 10.2+ MB